### PR TITLE
Adaptor -> Adapter

### PR DESCRIPTION
**Pull request by LeffelMania**

### CODE REVIEW

**Comment by philwebster** [comment]
giphy-4

**Comment by rex-remind101** [comment]
Lol, wow... I'll go ahead and run the tests locally and merge

**Comment by rex-remind101** [comment]
Oh wait, this is a fork. I'll just merge, run, and potentially fix then. Travis takes an eternity to start running. Really need to get to the bottom of why.

**Comment by rex-remind101** [comment]
@LeffelMania i just checked and you have push access fyi. I just added phil and jessie.

**Pull request merged**
